parameters:
    show_exception_token: t0k3n

framework:
    secret: S0ME_SECRET
    validation:
        enabled: true

tactician:
    commandbus:
        default:
            middleware:
                - logger_middleware.command_bus
                - tactician.middleware.validator
                - tactician.middleware.command_handler
